# Generated by Django 4.1 on 2022-08-14 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Not exist', max_length=350)),
                ('message', models.TextField(default='Not exist', max_length=10000)),
                ('isInWork', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
